### ISSUE TITLE
Cannot find module since v1.8.0

### ISSUE THREAD

**Issue by sm3sher** [bubkoo/html-to-image#187]
Build-time error when upgrading to 1.8.0 - 1.8.3:
```Cannot find module: 'html-to-image'. Make sure this package is installed.```

### Steps to reproduce
1. Upgrade to the latest version
2. Perform `npm run start` or `npm run build`
3. npm throws error

### Observations
The `html-to-image` folder in node_modules is missing `dist`, `es` and `lib`.

### Environment
- html-to-image: 1.8.3
- OS: macOS BigSur 11.5.2
- Browser: chrome 93.0.4577.63

**Comment by bubkoo** [comment]
@sm3sher fixed since v1.8.4.  ref https://github.com/bubkoo/html-to-image/commit/048e823f1dd5152b2f130ac3c752d640f11391ee

**Comment by nikossoftwaredev** [comment]
yes, we had anxiety in our work, we downgraded to 1.7

**Comment by sm3sher** [comment]
@bubkoo this is indeed fixed in v1.8.4.
